# This file was generated by GoReleaser. DO NOT EDIT.
class Crd2pulumi < Formula
  desc "Generate typed CustomResources in Pulumi from Kubernetes CRDs"
  homepage "https://pulumi.com"
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pulumi/crd2pulumi/releases/download/v1.0.5/crd2pulumi-v1.0.5-darwin-amd64.tar.gz"
    sha256 "930296f2794787a439b279dde4ea4ee73b52219852ffcec1530af251da670577"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/crd2pulumi/releases/download/v1.0.5/crd2pulumi-v1.0.5-linux-amd64.tar.gz"
      sha256 "c43fee2a38e920c3826dbe48c71c22f931aea91fbfbd6436aed39d6bb45b771f"
    end
  end

  def install
    bin.install "crd2pulumi"
  end
end
