# This file was generated by GoReleaser. DO NOT EDIT.
class Kube2pulumi < Formula
  desc "Convert Kubernetes manifests to Pulumi code"
  homepage "https://pulumi.io"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.1/kube2pulumi-v0.0.1-darwin-amd64.tar.gz"
    sha256 "91103486156e95bb4d3e7f248d7922b80d8d8ee52c65a5b7a15ca7dd620646c0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.1/kube2pulumi-v0.0.1-linux-amd64.tar.gz"
      sha256 "d28949973dd7e7c7a18f215ee3ec921be9b5c6d984cbe0a7ee37da30cf7f076c"
    end
  end

  def install
    bin.install "kube2pulumi"
  end
end
