# This file was generated by GoReleaser. DO NOT EDIT.
class Kube2pulumi < Formula
  desc "Convert Kubernetes manifests to Pulumi code"
  homepage "https://pulumi.io"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.3/kube2pulumi-v0.0.3-darwin-amd64.tar.gz"
    sha256 "b844c4cbff666dff3745deb98be4b478d8a18d4ac7bd6246a0105abfca9e3a75"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.3/kube2pulumi-v0.0.3-linux-amd64.tar.gz"
      sha256 "d4d21cc0d6ab6eba61bd0001687f67a0dfdc1fdf556d481d389e829f26cb9649"
    end
  end

  def install
    bin.install "kube2pulumi"
  end
end
