# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumictl < Formula
  desc "A swiss army knife for Pulumi development"
  homepage "https://pulumi.io"
  version "0.0.1-alpha"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pulumi/pulumictl/releases/download/v0.0.1-alpha/pulumictl-v0.0.1-alpha-darwin-amd64.tar.gz"
    sha256 "955605e1058a6e5f422b5b9ce6b8d84458c8d0ffaaae49b4f9a20b2dd77828c1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.1-alpha/pulumictl-v0.0.1-alpha-linux-amd64.tar.gz"
      sha256 "3bcd7f530a4131dd739414d44f63fcf0e7de6a3fa21fbfaba19dc597343c38a1"
    end
  end

  def install
    bin.install "pulumictl"
  end
end
