# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumictl < Formula
  desc "A swiss army knife for Pulumi development"
  homepage "https://pulumi.io"
  version "0.0.13"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pulumi/pulumictl/releases/download/v0.0.13/pulumictl-v0.0.13-darwin-amd64.tar.gz"
    sha256 "2bea7249ecff8459a8aface97a8e2f6c037badda0a30133934541bcac12bbdf9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.13/pulumictl-v0.0.13-linux-amd64.tar.gz"
      sha256 "db04746612edbc132f05e189acd581092c1d8779fdfb79f39b6aefa984e76a46"
    end
  end

  def install
    bin.install "pulumictl"
  end
end
