# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf2pulumi < Formula
  desc "A tool to convert Terraform projects to Pulumi programs"
  homepage "https://pulumi.io"
  version "0.11.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pulumi/tf2pulumi/releases/download/v0.11.0/tf2pulumi-v0.11.0-darwin-x64.tar.gz"
    sha256 "66e04339b53cf39d6022483b3c318998c9046fd99b365333a27297357ddc4bf5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pulumi/tf2pulumi/releases/download/v0.11.0/tf2pulumi-v0.11.0-linux-x64.tar.gz"
    sha256 "53488eed961ecf032761a5251de290ed780a12733abc8067450a32f0a54af736"
  end

  def install
    bin.install "tf2pulumi"
  end
end
