# This file was generated by GoReleaser. DO NOT EDIT.
class Tf2pulumi < Formula
  desc "A tool to convert Terraform projects to Pulumi TypeScript programs"
  homepage "pulumi.io"
  version "0.8.0"
  bottle :unneeded

  head do
    url "https://github.com/pulumi/tf2pulumi.git"
    depends_on "go@1.13" if build.head?
  end

  if OS.mac?
    url "https://github.com/pulumi/tf2pulumi/releases/download/v0.8.0/tf2pulumi-v0.8.0-darwin-amd64.tar.gz"
    sha256 "3b2531e1db292a1039658b9610c8c7513e9a4b4fc5a509bda2db5c92d340c573"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/tf2pulumi/releases/download/v0.8.0/tf2pulumi-v0.8.0-linux-amd64.tar.gz"
      sha256 "e4977893339949d11b79bdefdd3d011c59fd7bc5456e6f991ad055a4a5657b32"
    end
  end

  def install

    if build.head?
      ENV["GOPATH"] = buildpath
      ENV["GO111MODULE"] = "on"
      dir = buildpath/"src/github.com/pulumi/tf2pulumi"
      dir.install buildpath.children
      system "go", "build", "-ldflags=-X github.com/pulumi/tf2pulumi/version.Version=#{version}", "github.com/pulumi/tf2pulumi"
      bin.install Dir["#{buildpath}/tf2pulumi"]
    end

    if build.stable?
      bin.install "tf2pulumi"
    end

  end
end
