# This file was generated by GoReleaser. DO NOT EDIT.
class Tf2pulumi < Formula
  desc "A tool to convert Terraform projects to Pulumi TypeScript programs"
  homepage "pulumi.io"
  version "0.9.0"
  bottle :unneeded

  head do
    url "https://github.com/pulumi/tf2pulumi.git"
    depends_on "go@1.13" if build.head?
  end

  if OS.mac?
    url "https://github.com/pulumi/tf2pulumi/releases/download/v0.9.0/tf2pulumi-v0.9.0-darwin-x64.tar.gz"
    sha256 "fdecd3cd7734af74ece5f0f07d2bf4e67ebf372be7fb20003b0805ce91159593"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/tf2pulumi/releases/download/v0.9.0/tf2pulumi-v0.9.0-linux-x64.tar.gz"
      sha256 "525ebb6a4fac9ce9ee77942c65f4c08228d86fa582a385f0675001c4a753d096"
    end
  end

  def install

    if build.head?
      ENV["GOPATH"] = buildpath
      ENV["GO111MODULE"] = "on"
      dir = buildpath/"src/github.com/pulumi/tf2pulumi"
      dir.install buildpath.children
      system "go", "build", "-ldflags=-X github.com/pulumi/tf2pulumi/version.Version=#{version}", "github.com/pulumi/tf2pulumi"
      bin.install Dir["#{buildpath}/tf2pulumi"]
    end

    if build.stable?
      bin.install "tf2pulumi"
    end

  end
end
