# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arm2pulumi < Formula
  desc "A tool to convert Azure ARM Templates to Pulumi programs"
  homepage "https://pulumi.com"
  version "1.99.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.99.1/arm2pulumi-v1.99.1-darwin-x64.tar.gz"
      sha256 "4bf9b7676414820e6435d2875da4262afe8235da19ca620a01229670c06035eb"

      def install
        bin.install "arm2pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.99.1/arm2pulumi-v1.99.1-darwin-arm64.tar.gz"
      sha256 "50b06b05e43c42958ce48604911d94664165d788b54c1c2d82a5c61159df69ee"

      def install
        bin.install "arm2pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.99.1/arm2pulumi-v1.99.1-linux-arm64.tar.gz"
      sha256 "015b6670abf4e55b7147d90582e556cd5f0242b6c9933b86e82c7727ff94a630"

      def install
        bin.install "arm2pulumi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.99.1/arm2pulumi-v1.99.1-linux-x64.tar.gz"
      sha256 "b97007a84e2a8c87c230869b4b11f9989e41d2790dfdc7a0bbf5dc9123fe1cd0"

      def install
        bin.install "arm2pulumi"
      end
    end
  end
end
