# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arm2pulumi < Formula
  desc "A tool to convert Azure ARM Templates to Pulumi programs"
  homepage "https://pulumi.com"
  version "1.85.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.85.0/arm2pulumi-v1.85.0-darwin-x64.tar.gz"
      sha256 "69b09357a7d8772578fc8fed147fef76a97af41c2fb398e09310afb33c1ba9cb"

      def install
        bin.install "arm2pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.85.0/arm2pulumi-v1.85.0-darwin-arm64.tar.gz"
      sha256 "cd2527d0d998b386d0c78c72d7fa86ae0978c24dd190c0597ce67b2ebd304c4e"

      def install
        bin.install "arm2pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.85.0/arm2pulumi-v1.85.0-linux-x64.tar.gz"
      sha256 "198070fdb44871c4d216e95cf2fd56ca0c3703f03102903c9540ffa622f732ff"

      def install
        bin.install "arm2pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/pulumi-azure-native/releases/download/v1.85.0/arm2pulumi-v1.85.0-linux-arm64.tar.gz"
      sha256 "01657e8a9ab6e50f01fe1de690a4805ac187bfe2035fe9c4dd4423e137e34a53"

      def install
        bin.install "arm2pulumi"
      end
    end
  end
end
