# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cf2pulumi < Formula
  desc "A tool to convert CloudFormation Templates to Pulumi programs"
  homepage "https://pulumi.com"
  version "0.104.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.104.0/cf2pulumi-v0.104.0-darwin-x64.tar.gz"
      sha256 "0c1d134c4ddd832cce7c97e563fab6b283cb23962c7325bd66765387db951cd6"

      def install
        bin.install "cf2pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.104.0/cf2pulumi-v0.104.0-darwin-arm64.tar.gz"
      sha256 "cb7d79971cfff5a79f9ec7d377b6805b40e3ce0053a750430bdfa51a77598670"

      def install
        bin.install "cf2pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.104.0/cf2pulumi-v0.104.0-linux-x64.tar.gz"
      sha256 "854e78d4cf3755fe7b7a6757277831543bf67e1310163b6491ba1ef167abcd99"

      def install
        bin.install "cf2pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.104.0/cf2pulumi-v0.104.0-linux-arm64.tar.gz"
      sha256 "a6b56e246d0bbf89b204bc92db464f50aebf26f0d1e669122d3f18630f4683d6"

      def install
        bin.install "cf2pulumi"
      end
    end
  end

  test do
    system "#{bin}/cf2pulumi version"
  end
end
