# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cf2pulumi < Formula
  desc "A tool to convert CloudFormation Templates to Pulumi programs"
  homepage "https://pulumi.com"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.7.0/cf2pulumi-v0.7.0-darwin-x64.tar.gz"
      sha256 "e978a03c3cb095f22c584518a04864248dacc416818c0e76a0b60d8ac169646d"

      def install
        bin.install "cf2pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.7.0/cf2pulumi-v0.7.0-darwin-arm64.tar.gz"
      sha256 "6451fff847e0a1a1d40a17e5839790f10958953996dd555067ad1afde38598a6"

      def install
        bin.install "cf2pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.7.0/cf2pulumi-v0.7.0-linux-x64.tar.gz"
      sha256 "6613f1dc4fd8f4619cbf92aca9c448fcbf2041e994d33a7d3289b9080b6d2dba"

      def install
        bin.install "cf2pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/pulumi-aws-native/releases/download/v0.7.0/cf2pulumi-v0.7.0-linux-arm64.tar.gz"
      sha256 "08c3df666d1a2aa5fe7dfa529e3b37102b8868f0130dd5ef93c94ca6769682d8"

      def install
        bin.install "cf2pulumi"
      end
    end
  end

  test do
    system "#{bin}/cf2pulumi version"
  end
end
