# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crd2pulumi < Formula
  desc "Generate typed CustomResources in Pulumi from Kubernetes CRDs"
  homepage "https://pulumi.com"
  version "1.5.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/pulumi/crd2pulumi/releases/download/v1.5.4/crd2pulumi-v1.5.4-darwin-amd64.tar.gz"
      sha256 "a88c56a93df8ed4e563b69b878ca601db4316cd4ba096400728562e44e96651c"

      def install
        bin.install "crd2pulumi"
      end
    end
    on_arm do
      url "https://github.com/pulumi/crd2pulumi/releases/download/v1.5.4/crd2pulumi-v1.5.4-darwin-arm64.tar.gz"
      sha256 "79d1f906881003b0237c45f7e3ab8ae68fc252b35647fc3fb741ead06f00e3d5"

      def install
        bin.install "crd2pulumi"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pulumi/crd2pulumi/releases/download/v1.5.4/crd2pulumi-v1.5.4-linux-amd64.tar.gz"
        sha256 "0b335aff89bb8bfee29da2e9b5d76cce27b42e4419c4fe06c43e29569bdcba52"

        def install
          bin.install "crd2pulumi"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pulumi/crd2pulumi/releases/download/v1.5.4/crd2pulumi-v1.5.4-linux-arm64.tar.gz"
        sha256 "59c80da16d9755e7e1048d03e452b4a4e7f2362b7ae537dd152e828ee75ee960"

        def install
          bin.install "crd2pulumi"
        end
      end
    end
  end

  test do
    system "#{bin}/crd2pulumi version"
  end
end
