# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Esc < Formula
  desc "Pulumi ESC - Manage Environments, Secrets, and Configuration"
  homepage "https://pulumi.com"
  version "0.4.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/esc/releases/download/v0.4.5/esc-v0.4.5-darwin-arm64.tar.gz"
      sha256 "565a18125c4b0146743a0da14222119a3600c471d8472ad070c3efdb4453f3eb"

      def install
        bin.install "esc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/esc/releases/download/v0.4.5/esc-v0.4.5-darwin-amd64.tar.gz"
      sha256 "1f786c4c017d5c0dbbe0cb9e681f36ebbf7d8de09bd98d4c4de91f8b0dba4d12"

      def install
        bin.install "esc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/esc/releases/download/v0.4.5/esc-v0.4.5-linux-arm64.tar.gz"
      sha256 "b4b637604aafdae02596d8198e4d2fa10c971d3903874a2bbd65da0649ec96f1"

      def install
        bin.install "esc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/esc/releases/download/v0.4.5/esc-v0.4.5-linux-amd64.tar.gz"
      sha256 "56c2f30285e72502848c7a1c6f05316ce383d0a7b2a7b30515816355d619d067"

      def install
        bin.install "esc"
      end
    end
  end

  test do
    system "#{bin}/esc version"
  end
end
