# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kube2pulumi < Formula
  desc "Convert Kubernetes manifests to Pulumi code"
  homepage "https://pulumi.io"
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.15/kube2pulumi-v0.0.15-darwin-arm64.tar.gz"
      sha256 "fb1297e5514292c092ec2df70d6a464a38b8ad86d45ca362f134085374b5f99d"

      def install
        bin.install "kube2pulumi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.15/kube2pulumi-v0.0.15-darwin-amd64.tar.gz"
      sha256 "e8c57dfc04826120ef450e6da9d2ef7ef997e5362f4e869b54f1c5beba7ca42e"

      def install
        bin.install "kube2pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.15/kube2pulumi-v0.0.15-linux-arm64.tar.gz"
      sha256 "6b27f98d4a7b3909ab2378f7373796673edad8f017ce25a3f09d0fda13df49d0"

      def install
        bin.install "kube2pulumi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.15/kube2pulumi-v0.0.15-linux-amd64.tar.gz"
      sha256 "49814ef07e7b7546345c45306a62bcb7e47bc3f819611c74fdaf8d54f7f8b74b"

      def install
        bin.install "kube2pulumi"
      end
    end
  end

  test do
    system "#{bin}/kube2pulumi version"
  end
end
