# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kube2pulumi < Formula
  desc "Convert Kubernetes manifests to Pulumi code"
  homepage "https://pulumi.io"
  version "0.0.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.12/kube2pulumi-v0.0.12-darwin-amd64.tar.gz"
      sha256 "3d0591e73f7d9ed2813c8d0536b042630b64516aa5ed172940fc50b35fb31f93"

      def install
        bin.install "kube2pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.12/kube2pulumi-v0.0.12-darwin-arm64.tar.gz"
      sha256 "94d27f5b85e209f20bfbb68a0c6eb85c783b070306e10dda4c1c6bb9898f4f66"

      def install
        bin.install "kube2pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.12/kube2pulumi-v0.0.12-linux-amd64.tar.gz"
      sha256 "67063c29eb74af538e19647aa5233a07322494e4f0f2b8830df9291c508974be"

      def install
        bin.install "kube2pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/kube2pulumi/releases/download/v0.0.12/kube2pulumi-v0.0.12-linux-arm64.tar.gz"
      sha256 "2bb98f1ed39e5727eb5c6a3bf4dd917921422e8519ec570cf54524504c4408d8"

      def install
        bin.install "kube2pulumi"
      end
    end
  end

  test do
    system "#{bin}/kube2pulumi version"
  end
end
