# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumictl < Formula
  desc "A swiss army knife for Pulumi development"
  homepage "https://pulumi.io"
  version "0.0.28"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.28/pulumictl-v0.0.28-darwin-arm64.tar.gz"
      sha256 "970bc2e94674bc2860a13425afe7f383b08376f38c3ebcf71a3986493a8a303c"
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.28/pulumictl-v0.0.28-darwin-amd64.tar.gz"
      sha256 "3f3bbd35cad0bb68a9bbba16bc626ebd81edb47ed9ab3d457f8d2d7bf8a63b54"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.28/pulumictl-v0.0.28-linux-arm64.tar.gz"
      sha256 "72a90c0621ac6d29c3e502af20c611788826a0ebf6c162863ebd9857bfae3f56"
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.28/pulumictl-v0.0.28-linux-amd64.tar.gz"
      sha256 "e0e225f15f325790f1694b70803340eeb08c599337f425498384dbd65288346a"
    end
  end

  def install
    bin.install "pulumictl"
  end

  test do
    system "#{bin}/pulumictl version"
  end
end
