# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumictl < Formula
  desc "A swiss army knife for Pulumi development"
  homepage "https://pulumi.io"
  version "0.0.25"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pulumi/pulumictl/releases/download/v0.0.25/pulumictl-v0.0.25-darwin-amd64.tar.gz"
    sha256 "9e2128043a2b1543a0daea86549b0bb7e170d19f16ad64bdbac2c6421b20bec4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/pulumictl/releases/download/v0.0.25/pulumictl-v0.0.25-linux-amd64.tar.gz"
      sha256 "27a428cd27ef0469d56a74ffd456658b3f82424be1a295e530d6953825954c25"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pulumi/pulumictl/releases/download/v0.0.25/pulumictl-v0.0.25-linux-arm64.tar.gz"
        sha256 "f17094744405e104362ce8220648234e9afa489c05aa5d1fd11fd9db3b087204"
      else
      end
    end
  end

  def install
    bin.install "pulumictl"
  end
end
