# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Registrygen < Formula
  desc "Creation of Pulumi Package Metadata and API Docs for use in the Pulumi Registry"
  homepage "https://pulumi.io"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.8/registrygen-v0.0.8-darwin-arm64.tar.gz"
      sha256 "1ebb72f90626c20d934f61dccb345d8dc6f3e73048ad69b5ab006dba114a12aa"

      def install
        bin.install "registrygen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.8/registrygen-v0.0.8-darwin-amd64.tar.gz"
      sha256 "bc51903e373b9ff8f797d5001ccc861a5b226bc5309f4582dc32a9041b061729"

      def install
        bin.install "registrygen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.8/registrygen-v0.0.8-linux-arm64.tar.gz"
      sha256 "6d65b110f8db2083afdfdad17ad2bb71c8aa7dfcf30f487bda34563d520aa715"

      def install
        bin.install "registrygen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.8/registrygen-v0.0.8-linux-amd64.tar.gz"
      sha256 "62303ff43b85e3205a7f8a2670e6056653f1d2e19678b518295a6e6ebc3e1fb1"

      def install
        bin.install "registrygen"
      end
    end
  end

  test do
    system "#{bin}/registrygen help"
  end
end
