# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Registrygen < Formula
  desc "Creation of Pulumi Package Metadata and API Docs for use in the Pulumi Registry"
  homepage "https://pulumi.io"
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.15/registrygen-v0.0.15-darwin-arm64.tar.gz"
      sha256 "db2a6826c14423c2fd6a869dda4bb6ec1515df40f46d911009fb071f7dcd59b9"

      def install
        bin.install "registrygen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.15/registrygen-v0.0.15-darwin-amd64.tar.gz"
      sha256 "0d6cb31d044de1d0045d1536185cdd03177337783fadcc9c97441f68461208f8"

      def install
        bin.install "registrygen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.15/registrygen-v0.0.15-linux-amd64.tar.gz"
      sha256 "5eca64c6af7b97ef51f02659d72186c244c61a5720064bf60c5503f855399545"

      def install
        bin.install "registrygen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pulumi/registrygen/releases/download/v0.0.15/registrygen-v0.0.15-linux-arm64.tar.gz"
      sha256 "4f49806b43223d60ea1d0fa71c93c16c59648aaf0dde2e07d5e3422558bdc589"

      def install
        bin.install "registrygen"
      end
    end
  end

  test do
    system "#{bin}/registrygen help"
  end
end
