name: CI

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: Push to `master`
        run: |
          git push origin HEAD:main
