permissions: write-all # Equivalent to default permissions plus id-token: write
name: CI

on:
  push:
    branches:
      - main

env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
          fetch-depth: 0
      - name: Push to `master`
        run: |
          git push origin HEAD:master
